### ISSUE TITLE
GitHub dependents not detected

### ISSUE THREAD

**Issue by drewnoakes** [microsoft/MSBuildSdks#107]
https://github.com/microsoft/MSBuildSdks/network/dependents

The nuspec files here are stopping GitHub from showing who is using these SDK packages, presumably due to `<packageId>$id</packageid>` syntax.

Not a biggie, but I was looking for some usages of these SDKs to learn more about their use.

**Comment by jeffkl** [comment]
I'm not sure if GitHub would detect the dependency since users would reference them as `<Sdk />` and not `<PackageReference />`.  Do you know how the dependencies detection works?

**Comment by drewnoakes** [comment]
I'm not 100% sure how it works. Perhaps if the package itself specifies a GitHub repo. I did have one case where a csproj specified two `<ProjectId>` elements based on conditions and GitHub failed to resolve the ID. In this repo it's a nuspec.

But I think you're right that the `<Sdk>` references wouldn't be detected as references.

I'll close this.

**Comment by tompazourek** [comment]
This issue is probably because the Network Dependents haven't been working well on GitHub for quite a long time. So it's possibly not your issue, but GitHub's issue.

I raised this issue on their forum, but not much progress happened yet: https://github.community/t/bug-project-not-showing-network-dependents/3161
