### ISSUE TITLE
CentralPackageVersions: Microsoft.AspNetCore.All should be excluded even for non web sdk projects

### ISSUE THREAD

**Issue by twmillett** [microsoft/MSBuildSdks#144]
This fix for [this issue](https://github.com/microsoft/MSBuildSdks/issues/118) conditioned implicit versioning to Microsoft.Net.SDK.Web projects.  Our project has libraries that just use Microsoft.Net.SDK.

Microsoft.Net.SDK.Web has a bunch of [implications](https://github.com/aspnet/Tooling/issues/486) that makes converting these projects to it undesirable.

Is it necessary to condition the implicit versioning fix to just projects that use the web SDK?

**Comment by jeffkl** [comment]
How are you referencing the `Microsoft.AspNetCore.App` and `Microsoft.AspNetCore.All` packages?  The main intent of https://github.com/microsoft/MSBuildSdks/pull/119/files was to mark them as implicitly defined for projects using `Microsoft.NET.Sdk.Web`.  If you're using a different project type you'd probably need to add the package references yourself.  You can add the same metadata if needed.

```xml
<ItemGroup>
  <PackageReference Include="Microsoft.AspNetCore.All" Version="2.2.8" IsImplicitlyDefined="true" />
</ItemGroup>
```

And if you're using CentralPackageVersions you can do it like this in the project:

```xml
<ItemGroup>
  <PackageReference Include="Microsoft.AspNetCore.All" />
</ItemGroup>
```

And this in Packages.props:
```xml
<ItemGroup>
  <PackageReference Update="Microsoft.AspNetCore.All" Version="2.2.8" />
</ItemGroup>
```

I'm not very familiar with web projects at the moment, so maybe that's all wrong?  But I'd be open to setting the IsImplicitlyDefined metadata depending on how you're adding the PackageReference.

**Comment by twmillett** [comment]
Maybe I should start from the beginning.   The TLDR, though is that I have a workaround by adding the IsImplicitlyDefined attribute to Packages.props (see below).

So, before trying to migrate to central package versioning, the individual .csproj looked like this.  Since 2.1, the [recommendation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage?view=aspnetcore-3.1) has been to reference it this way, without a version.

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" />
  </ItemGroup>
```

After wiring up central package versioning, I added this to Package.props, also without a version.

```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <PackageReference Update="Microsoft.AspNetCore.App" />
  </ItemGroup>
```

That results in the error, from central package versioning, 

```
 error : The package reference 'Microsoft.AspNetCore.All' must have a version defined in 'Packages.props'.
``` 

So, I changed the Packages.props to include a version

```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <PackageReference Update="Microsoft.AspNetCore.App" Version="2.2.8"/>
  </ItemGroup>
```

But, that fails with this error from the SDK, because it's in violation of the recommendation to not specify a version:

```
warning NETSDK1071: A PackageReference to 'Microsoft.AspNetCore.All' specified a Version of `[2.2.8]`. Specifying the version of this package is not recommended. For more information, see https://aka.ms/sdkimplicitrefs
```

So, there are competing requirements between central package versioning and the sdk -- one insists on a version, the other prohibits it.

I found the fix [here](https://github.com/jeffkl/MSBuildSdks/commit/c011280827e68b08427d0762e132b62ba2e5d67a) 

fixes the conundrum for projects that use

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
```

but is does not fix it for projects that use

```xml
<Project Sdk="Microsoft.NET.Sdk">
```

The reason is the condition on the fix, which scopes the IsImplicitlyDefined attribute to just projects using the web sdk.

```xml
<PackageReference Update="Microsoft.AspNetCore.All"
                      Condition="'$(UsingMicrosoftNETSdkWeb)' == 'true'"
                      IsImplicitlyDefined="true" />
```

I fixed things, on my side, but adding IsImplicitlyDefined in Packages.props.  So, the csproj stays just as it did before migration, and the Packages.props looks like

```xml
    <PackageReference Update="Microsoft.AspNetCore.All"
                      IsImplicitlyDefined="true" />

```

(Note, I do not have the Version attribute).

What I'm wondering is why the fix here [added](https://github.com/jeffkl/MSBuildSdks/commit/c011280827e68b08427d0762e132b62ba2e5d67a) that condition to begin with, and if it should be removed.

**Comment by jeffkl** [comment]
Awesome that detail really helps.  The only thing I don't understand is when you're allowed to not use `Microsoft.NET.Sdk.Web` as the project SDK.  Even the documentation you linked to shows using that SDK and not the `Microsoft.NET.Sdk`.  Where is there official guidance that when you're building a ASP.NET Core application, its okay to use `Microsoft.NET.Sdk`?  

Also, going forward it looks like you won't need this PackageReference anymore:

https://github.com/dotnet/sdk/blob/f98197d56b051f8c5078e9017de1ef7046125205/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.targets#L147

As long as your project SDK is `Microsoft.NET.Sdk.Web` then a implicit `FrameworkReference` is added and any `PackageReference` is removed.

It seems like as long as you're referencing the documented SDK, things just work and you're only in this spot because you're referencing the "wrong" SDK.  You might know more about this ASP.NET Core stuff than me though, so please set me straight if I'm wrong.

**Comment by twmillett** [comment]
That's interesting about `FrameworkReference`.  Thanks for pointing that out.

I'm not sure about the official guidance about referencing Microsoft.NET.Sdk from an ASP.NET core app.  Our repo has a lot of different projects -- one, the "startup" project with the "Main" entrypoint, etc, references the `Microsoft.NET.Sdk.Web`.  But, other projects in the repo are just library DLLs the main project consumes.  These reference `Microsoft.NET.Sdk`.

**Comment by jeffkl** [comment]
I think I'll just recommend your workaround unless we can find more official guidance on when to use the combination of `Microsoft.NET.Sdk` and an explicit PackageReference to `Microsoft.AspNetCore.All`.  In my opinion its sort of a bug that the version of `Microsoft.AspNetCore.All` is set for you even if you don't reference the recommended SDK.  It would make more sense to me if you referenced `Microsoft.NET.Sdk` and `Microsoft.AspNetCore.All` that you would need to specify your own version.  

I don't feel real strong about it either way, if you want to send a PR to remove the condition I'd accept it (since it seems to sort of work even though it probably shouldn't).

**Comment by jeffkl** [comment]
Closing since there's a workaround
