### ISSUE TITLE
Microsoft.Build.NoTargets project expects incorrect ouput 

### ISSUE THREAD

**Issue by davkean** [microsoft/MSBuildSdks#148]
(Moved from https://github.com/dotnet/project-system/issues/5868)

**Visual Studio Version**: 16.4.4

**Summary**:
Having a project with Microsoft.Build.NoTargets is never up-to-date because it expects an output that is never generated.

**Steps to Reproduce**:

1. Create and SDK project.

2. Update the project to be Microsoft.Build.NoTargets. See mine:
<Project Sdk="Microsoft.Build.NoTargets">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
</Project>

I also had to add the following global.json:
{
  "msbuild-sdks": {
    "Microsoft.Build.NoTargets": "1.0.85"
  }
}

3. Build twice

**Expected Behavior**: The project should be up to date.

**Actual Behavior**: The project is not up to date because it expects the pdb file. Here is the log:
1>FastUpToDate: Adding UpToDateCheckBuilt outputs: (RepoNoTargetsBug)
1>FastUpToDate:     'C:\Users\edgarsil.000\source\repos\RepoNoTargetsBug\RepoNoTargetsBug\obj\Debug\net472\RepoNoTargetsBug.pdb' (RepoNoTargetsBug)
1>FastUpToDate: Output 'C:\Users\edgarsil.000\source\repos\RepoNoTargetsBug\RepoNoTargetsBug\obj\Debug\net472\RepoNoTargetsBug.pdb' does not exist, not up to date. (RepoNoTargetsBug)

**User Impact**:
Project is never up to date.

**Comment by davkean** [comment]
These projects are "csproj" yet don't produce outputs so moved over to here, this is not something (C#/VB project team) support.

**Comment by jeffkl** [comment]
I'm not sure if this can be fixed.  NoTargets projects can emit anything or nothing at all.  I changed it to not expect to emit a .pdb or .dll but then the build never happens in Visual Studio since it thinks everything is up-to-date.

We could possibly add guidance so that users could opt into fast up-to-date check in VS but out of the box it would have to always build.  Users could then be told to make sure they have targets set up with Inputs and Outputs so they're at least getting incremental builds within MSBuild.  

Standard C# projects almost always emit an assembly and optionally emit symbols, XML documentation, and application configurations.  But NoTargets projects have no expectations.  We only name them `.csproj` so they'll load in Visual Studio.  Another option would be to write our own project system, `NoProj` but that would be a lot of effort.  

I'll leave this issue open to collect feedback from the community.

**Comment by davkean** [comment]
"csproj" are for C# projects that produce C# binaries, not a general purpose project system for running build targets. I understand what you are trying to achieve, but you are fitting a square plug in a round hole. 

"msbuildproj" is probably a lot closer to to what you want and you should investigate that approach, alternatively, register your project system and implement the behavior you would like.

**Comment by dotMorten** [comment]
I think I'm hitting this too. Because I use this to generate a package with just native assemblies (ie just content/runtimes) that are then a dependency to other projects, this project is basically causing my entire solution to build again and again each time, making the developer loop extreeeeeemely slow.

Reproducer: [RebuildBug.zip](https://github.com/microsoft/MSBuildSdks/files/4905905/RebuildBug.zip)

**Comment by MeikTranel** [comment]
i agree the project system approach seems overwhelming ,@jeffkl... but i don't think it's entirely unreasonable. Stuff like meta-package projects or entirely custom but architected to fit the msbuild narrative projects go up in flames pretty fast when added to a solution. There's almost definitely a market for that. (i have a project that currently abuses the Traversal-SDK to do something that more or less follows what the csproj does - but can't use NoTargets because then i'd have to clutter the project with a whole lot of nonsense targets to avoid risking issues with msbuild task calls where SkipNonExistentTargets is false)

On the other end i think putting up guidance on how to reroute the fastuptodate to consider their specific in/outputs is sanest solution for now.

I'd personally be interested to see what impact this currently has - when its always not up-to-date, is it just a projectreference problem where other projects need to rebuild as well?

**Comment by aaronla-ms** [comment]
> We only name them .csproj so they'll load in Visual Studio.

Seconded. We've been asking for a _long_ time to have a generic project type for VS that it would ignore apart from project references and build order, just so we can load and view and build those dependencies. We even have a few service fabric projects that are mangled enough that they fail to load with the service fabric extensions in vs, so we renamed them .csproj just so they'll load and build under VS.

Because of this gap in vs support, .csproj has effectively become the defacto standard for "any project Visual Studio doesn't understand"

**Comment by MeikTranel** [comment]
I just tested this again - i seemed to remember that we had an update regarding *.msbuildproj files and so far its good:
![image](https://user-images.githubusercontent.com/6466560/110699326-053d4380-81ef-11eb-91dc-65f8d1e208e1.png)


FastUpToDate still doesnt help and i wasnt yet able to tell it to not look for outputs, but without doing anything it least doesnt change the UpToDate'ness of projects referencing it.

I tried to manually remove it to not rebuild the msbuildproj all the time but no luck yet:

![image](https://user-images.githubusercontent.com/6466560/110699698-6e24bb80-81ef-11eb-976b-969da0cd1823.png)

![image](https://user-images.githubusercontent.com/6466560/110699830-90b6d480-81ef-11eb-8cdf-f1e922371986.png)

This does not solve the issue at hand yet but at least the underlying conversation can be stirred back to the actual issue - maybe @davkean knows why it (UpToDateCheckBuilt items) can't be cleared entirely?

**Comment by jeffkl** [comment]
At this time, the solution is to provide to the FastUpToDate check what files take part in the check.
