### ISSUE TITLE
Unable to install MSBuildSdk due to "unsupported package type"

### ISSUE THREAD

**Issue by tyh77** [microsoft/MSBuildSdks#176]
Two questions:
1. Is **CentralPackageVersions** already part of the MSBuild engine? Do I need to install it via NuGet?
2. In my attempt to install the CentralPackageVersions sdk for projects in my solution via the VS19 Nuget Package Manager UI, I get the following error:

`Microsoft.Build.CentralPackageVersions 2.0.52' has a package type 'MSBuildSdk' that is not supported by project...`

Am I missing something?

**Comment by jeffkl** [comment]
MSBuild project SDKs are special packages that you can't use as a `<PackageReference />`.  Please review the docs for more info:
https://github.com/microsoft/MSBuildSdks#how-can-i-use-these-sdks

**Comment by timhuang77** [comment]
Hi Jeff,

My projects are using a separate packages.config, so I'm not sure I follow exactly what you mean.

Is there another way to install this SDK without Nuget?

Thanks!

-Tim

**Comment by jeffkl** [comment]
The project itself must reference the SDK with special elements, the most common of which is `<Sdk />`.  It should be spelled out clearly in the documentation link: https://github.com/microsoft/MSBuildSdks#how-can-i-use-these-sdks

Please review the docs and see if that answers your question.

**Comment by timhuang77** [comment]
I read through the documentation. I have referenced the SDK within the csproj file like such:
`<Sdk Name="Microsoft.Build.CentralPackageVersions" Version="2.0.52" />`

But to obtain the SDK in the first place, don't I have to obtain it through Nuget?

Nuget is still throwing me the following error:
`Package 'Microsoft.Build.CentralPackageVersions 2.0.52' has a package type 'MSBuildSdk' that is not supported by project '<ProjectName>'.`

The csproj is of SDK style and I would be able to reference the SDK as mentioned before

**Comment by jeffkl** [comment]
By referencing the package as an MSBuild project SDK, MSBuild will request NuGet to download the package for you when the project is loaded.  You do not need to reference the package in any other way.  So you don't need a `<PackageReference />` or add it to `packages.config`.  You can also place the `<Sdk />` element in `Directory.Build.targets so you don't need to reference it in every project in your tree.

**Comment by timhuang77** [comment]
Thanks Jeff. Actually this information helps a lot to help fill-in some of the context gap.

And although this is probably not directly due to MSBuildSdks, I'm encountering the following error upon build:
`Package WebApi.Enhancements 0.5.0 is not compatible with net462 (.NETFramework,Version=v4.6.2) / win7-x86. Package WebApi.Enhancements 0.5.0 supports: 40full (40-Full,Version=v0.0)`

Though WebApi.Enhancements is not a package that we use (probably a dependency of some NuGet package), have you seen this on any user experiences before? This error is a direct result of adding the Sdk to the project.

**Comment by timhuang77** [comment]
Hi @jeffkl ,

Do these SDK's support non-SDK-style project files (packages.config)? My project is running a few ASP.NET apps that seemingly cannot be migrated to the SDK-style projects:
[https://github.com/NuGet/docs.microsoft.com-nuget/issues/1342](url)

To apply the SDK to all the projects in the directory tree, I have added the sdk to `Directory.build.targets`, but I'm wondering what this effect has on a non-SDK-style project files that do not have `<PackageReference />` for every NuGet dependency. 

My guess is that CentralPackageVersions only enforces on tags with `PackageReference`? So if the project file has absent `PackageReference` tags then it'll simply not catch those? 

Although not ideal, this might potentially be sufficient for our purposes (to have it simply ignore absent depedencies, for now)

**Comment by jeffkl** [comment]
Yes it works for non SDK-style (legacy) projects.  But if the project is using `packages.config` then its disabled.  Some project types still don't support `<PackageReference />` so it won't work for them yet.

**Comment by jeffkl** [comment]
Assuming this is resolved, feel free to re-open if not.

**Comment by auraboldizsar** [comment]
Hi, 

What if we are not allowed (due to CI/CD setup) to download the SDK from online nuget source but to download and reference it from internal nuget source? How should the following config line look like?

<Project Sdk="MSBuild.Sdk.SqlProj/2.0.0">

Thank you.

**Comment by MeikTranel** [comment]
@tyh77 
> Do these SDK's support non-SDK-style project files (packages.config)? My project is running a few ASP.NET apps that seemingly cannot be migrated to the SDK-style projects:


Try this:
https://github.com/CZEMacLeod/MSBuild.SDK.SystemWeb


As for @auraboldizsar - please don't hijack issues for completely unrelated questions that you should have asked the people who put these restrictions on CICD setup - not much jeff can help with problems like that.

**Comment by auraboldizsar** [comment]
@MeikTranel please see below the issue I experience. 

` error : Unable to find package MSBuild.Sdk.SqlProj. No packages exist with this id in source(s): nuget.org
[16:41:50][       Target "_FilterRestoreGraphProjectInputItems"]        MSB4236: The SDK 'MSBuild.Sdk.SqlProj/2.0.0' specified could not be found.
[16:41:50][       Target "_FilterRestoreGraphProjectInputItems"]        MSB4236: The SDK 'MSBuild.Sdk.SqlProj/2.0.0' specified could not be found.`

![image](https://user-images.githubusercontent.com/99972517/173237758-9ab2d22f-43a6-45d5-8d7b-141cae140c0b.png)

Definitely not trying to waste your time, but use this SDK and make it working so that I can advise other teams in my company how to properly use it. The people responsible with the CI/CD setup said they've added both MSBuild.SDK.SqlProj and MSBuild.SDK.SqlProj.templates to the internal artifactory and installed the project templates on the TeamCity agent but that did not fix the issue.
