### ISSUE TITLE
Feature Request, consider merging CPV with global.json

### ISSUE THREAD

**Issue by aaronla-ms** [microsoft/MSBuildSdks#226]
Currently, there are two separate mechanisms for centralized package version management of two kinds of nuget packages

- Sdk nugets, where versions may be centrally managed in the global.json, section msbuild-sdks
- PackageReference nugets, where versions may be centrally managed using the Microsoft.Build.CentralPackageVersions Sdk.

Is there any chance we could merge these two mechanisms into one list?

**Comment by jeffkl** [comment]
Unfortunately this is not possible at the moment.  MSBuild project SDKs are resolved _before_ projects are evaluated and therefore cannot be declared inside of a project except in the following ways:
```xml
<Project Sdk="Foo/1.0.0">
...
</Project>
```
The drawback of this is the version is declared in the project and not centrally.

```xml
<Project>
  <Sdk Name="Foo" Version="1.0.0" />
</Project>
```
As long as this is an import that every project pulls in, this effectively places the version in one place.  This works well for some MSBuild project SDKs (CentralPackageVersions since its only declared once) but not others (NoTargets is declared in each project).

```xml
<Import Project="Sdk.props" Sdk="Foo" Version="1.0.0" />
```
Similar to the one above, this works if every project imports that logic but won't work well for NoTargets.

If you're only using `Microsoft.Build.CentralPackageVersions`, you can use the `<Sdk />` element in `Directory.Build.targets` and have the version in there, meaning you won't need a version in `global.json`.  But as soon as you want to use `Microsoft.Build.NoTargets` in a handful of projects across the repo, you'll need the version in `global.json` to keep it in one place.

NuGet packages and their versions must be declared in projects because that's currently how NuGet is designed.  It cannot read `global.json`.  I doubt that would ever be supported but you can always ask.

https://github.com/nuget/home/issues/new

**Comment by aaronla-ms** [comment]
Thanks for the prompt response. I'm not following what you mean when you say "doens't work well for NoTargets". We're currently managing the version for NoTargets centrally. Inclusion in global.json doesn't automatically inject Microsoft.Build.NoTargets into every project into the repo -- it just provides a version number if/when a project references Sdk="Microsoft.Build.NoTargets" without a version.

I'm not asking on the nuget project because the CPV nuget package isn't build by the nuget team, it's hosted in this project. Couldn't it use an msbuild task to read global.json and update the PackageReference item group?

**Comment by jeffkl** [comment]
There are some limitations on how you declare items and properties in MSBuild.  Any item declared outside of a target is evaluated immediately by MSBuild and before any targets or tasks have run.  In Visual Studio, the NuGet restore happens before any targets are run based on the results of the evaluation of the project.  This means that no tasks can update these PackageReference items in that scenario.  When you restore from the command-line, you could technically do it since NuGet actually runs a target.

So without some more advanced feature in MSBuild and NuGet, there is no way to have all the versions in one place.  The versions for each system (MSBuild project SDK and PackageReference) can have their respective versions in one place at least.

**Comment by aaronla-ms** [comment]
> In Visual Studio, the NuGet restore happens before any targets are run based on the results of the evaluation of the project.

Any change of getting that fixed in some future release? The `CollectPackageReferences` bears the documentation: 

>

**Comment by jeffkl** [comment]
Closing this for now since the changes would have to be in MSBuild and NuGet.

**Comment by aaronla-ms** [comment]
> Closing this for now since the changes would have to be in MSBuild and NuGet.

Should this issue be reopened in a different project? Or  just punting on the idea of centrally managed package versions?

**Comment by jeffkl** [comment]
> Should this issue be reopened in a different project? Or just punting on the idea of centrally managed package versions?

_If_ this was ever improved, the versions would need to be in a file that is not MSBuild.  However, normal NuGet package consumption really needs MSBuild logic so you can conditionally use packages based on target framework, runtime, etc.

I know it seems weird that MSBuild project SDK versions are in one place and NuGet package versions are in another, especially since some MSBuild project SDKs can be NuGet packages themselves.  But they really serve different purposes in my opinion, so having their versions in different places seems reasonable.  You can open an issue against [NuGet](https://github.com/NuGet/Home/issues/new), anything is possible if enough people want it.

**Comment by aaronla-ms** [comment]
> But they really serve different purposes in my opinion, so having their versions in different places seems reasonable.

That's fine. If neither set of folks want there to be a central file for package management, it's not my place to tell them otherwise :). That, and there's definitely room for someone else to come along any add a 3rd central versioning location and provide both PackageReference version and Sdk version resolution in their solution. 

Thanks for your consideration.
