### ISSUE TITLE
Transitive dependency pinning

### ISSUE THREAD

**Issue by avivanoff** [microsoft/MSBuildSdks#283]
Would it be possible to implement transitive dependency pinning, something similar to [proposed NuGet implementation](https://github.com/NuGet/Home/issues/10389)?

**Comment by lazy8** [comment]
> Would it be possible to implement transitive dependency pinning, something similar to [proposed NuGet implementation](https://github.com/NuGet/Home/issues/10389)?

I can only second that request. 

We are stuck with dotnet 5.0.1XX because transitive pinning got turned off without any alternative for reactivation.
We have multiple big solutions containing plugins that need to run together, so ALL their DLLs need to be synchronized in the final application. CPVM was THE solution for us, and we were overjoyed to see this feature, but now, in its current state, it's pretty useless to us (again).

**Comment by lazy8** [comment]
Hi @jeffkl, thanks for your reply. I think there is a misunderstanding, the implementation for CPVM in dotnet 5.0.1XX (nuget 5.8) was working perfectly well for us. It just got destroyed in nuget 5.9 with no way to get it back.

Before 5.9, you could write a package version into `Directory.Packages.props` and it would be respected in all projects below, also if that package was "just" a transitive dependency in the project at hand.
From 5.9 onwards, this project will restore any version it want of that package, until you manually add the transitive dependency as a "fake" direct dependency.

So, yes, there was no auto-magic to resolve e.g. "Newtonsoft.Json" to the same version everywhere, but once you specified its version in the central file "manually", it would resolve to that version everywhere.

Internally, as a build test if you like, we parse all restored projects via "dotnet list packge --include-transitive" and fail if the resolved versions diverge for any package. Before 5.9, I could then just go and pin the version and be done with it. 
In 5.9 (and later), I would also have to make it a direct dependency everywhere where it's currently used implicitly. And that is basically unmaintainable.

**Comment by jeffkl** [comment]
Again, `Microsoft.Build.CentralPackageVersions` is only specifying versions of top-level/non-transitive dependencies with some fancy MSBuild logic and implementing enforcement to ensure users don't try to add versions to PackageReference items in projects.  But until NuGet itself considers versions for packages that aren't at the top level, then `Microsoft.Build.CentralPackageVersions` can't inject this logic.  It could look up the transitive closure on the fly and inject the explicit reference but that would be very slow.

We'll need to wait until NuGet understands out of the box that a particular version should be used transitively.

**Comment by CZEMacLeod** [comment]
@lazy8 and @jeffkl  For clarity, Transitive Pinning was a feature in NuGet for a while, but it was removed, which will be why it worked in NuGet 5.8 but not in 5.9 onwards.
https://github.com/NuGet/Home/issues/10132
https://github.com/NuGet/NuGet.Client/pull/3719
https://github.com/NuGet/Home/issues/10389
https://github.com/NuGet/NuGet.Client/pull/4025

**Comment by jeffkl** [comment]
Closing as won't fix since this SDK can't control the dependency graph created by NuGet.  The built-in central package version management in NuGet _might_ support this in future release.

**Comment by jeffkl** [comment]
@avivanoff 
> since NuGet now supports [transitive pinning](https://devblogs.microsoft.com/nuget/introducing-central-package-management/), what do we need to do to take advantage of it while using Microsoft.Build.CentralPackageVersions?

We have no plans to support transitive pinning in `Microsoft.Build.CentralPackageVersions`.  Since shipping `Microsoft.Build.CentralPackageVersions` I've actually joined the NuGet team and am working on the built-in central package management.  My plan is to deprecate `Microsoft.Build.CentralPackageVersions` in favor of that implementation instead and hopefully have time to write a migration tool.
