### ISSUE TITLE
Question: Custom SDK versioning

### ISSUE THREAD

**Issue by ivanpovazan** [microsoft/MSBuildSdks#299]
As far as I can see the Nu-Get based resolver does not support versioning wildcards.

Is there a plan to support custom SDK versions in the same fashion as nuget package versioning? 

For example in order to always reference the highest stable version one could specify it in the project file:
`<Project Sdk="MyCustom.Sdk/*">`
or in global.json
`
"msbuild-sdks": {
    "MyCustom.Sdk": "*"
}
`

**Comment by MeikTranel** [comment]
First and foremost: this isnt really the right repo for the question at hand. This repo contains a couple of advanced usecase sdks and doesnt control the infrastructure behind the nugetsdkresolver. The repo for that would be either https://github.com/dotnet/msbuild or https://github.com/NuGet/Home

As for the question itself i would argue that building on using that feature is kind of a fruitless endeavor; not that there is no place for wildcards, but you have to look at it this way. ````PackageReference``` entries with wild cards or range bounds arent even a well supported element yet - last i checked lock file usage to support deterministic builds is almost non-existent in open source projects, `dotnet pack` still writes in the used package version instead of the version requirements and third party tools and IDEs mostly dont even know about this feature.
Sure - the fundamentals are mostly equal since SDK references are just PackageReference elements with slightly different evaluation orders in the msbuild process - so it is definitely legitimate to bring this up to the team.
But on the other hand we have to look at what this would serve:

`global.json` was meant to lock down tooling around a work space. Back in the net framework days the project system team constantly had to integrate new code into old infrastructure. Visual Studio had to support opening up a 8 year old project file as if its a fresh off the press project. Thats why we commonly saw swaths of edits with weird PathCombines around visualstudioversion properties when we opened them. Every different version of the tooling had to prepare the workspace to their needs. With `global.json` visual studio just opens the files and if it doesnt support the sdk at all it just doesnt work. But nobody compiles a project and doesnt notice that some settings might be completely different to the build of their colleagues.
Introducing WildCard support here would be akin to throwing the back in the roulette table everytime a workspace meets a new environment.

In general wildcards are really just asking for trouble. Its counterproductive in the teams effort to establish a chain of trust where others (NPM) have failed.
Though sometimes there's room for compromises - we already established a mechanism to support rolling forward since the dominating force - Visual Studio - started bundling/managing your primary dotnet sdk and strict version requirements made checking out new workspaces really tedious. 
Maybe there's room to offer patch version roll forward for custom sdks as well (anyone whos ever tried rollling forward major or even minor version will probably quickly snap back to patch rollforward only anyways).

**Comment by ivanpovazan** [comment]
Thank you for the answer. The reason I asked the question on this repo was more for the fact that I was not sure if the versioning with wild cards is not supported or that I failed to configure my projects correctly.

As for the use case, we provide our customers with COBOL, PL/1 and HLASM full development experience in VisualStudio. Using custom SDKs for custom builds and projects works as intended, but the problem arises when it comes to versioning. If we increase the version number on each update of our language service, old project will stop working i.e. we will lose backward compatibility. 

Some kind of project upgrade would have to be introduced to update version numbers for custom SDK references on all existing projects. However, having NuGet package versioning for such cases would save us the troubles.

**Comment by MeikTranel** [comment]
Well first of all: 
> As for the use case, we provide our customers with COBOL, PL/1 and HLASM full development experience in VisualStudio.

i love it. 

As for the viability question - have you looked at not depending on the NuGetSdkResolver but instead of that just adding your own resolver? https://github.com/dotnet/msbuild/issues/2278 MSBuild already has the ability to search for resolver dlls implementing https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.framework.sdkresolver.

That way you have full control and you could drop the weird coexistence of your customsdk reference as well as a microsoft.net.sdk reference that you probably use atm.

Also i recommend reading up on https://github.com/microsoft/vsprojectsystem if you havent already. For dotnet the implementation lives under https://github.com/dotnet/project-system - it sounds like you're doing something similar already.

**Comment by ivanpovazan** [comment]
Thank you for the hints, I will take a look into other possible solutions.
