### ISSUE TITLE
BuildTraversal and restore target

### ISSUE THREAD

**Issue by avivanoff** [microsoft/MSBuildSdks#313]
Given the following traversal project:

```
<Project Sdk="Microsoft.Build.Traversal">

  <ItemGroup>

    <ProjectReference Include="C:\Proj\MySolution.sln" />

  </ItemGroup>

</Project>
```

I am getting errors when running Restore target:

```
"C:\Proj\build.proj" (Restore target) (1) ->
       (_GenerateRestoreGraph target) ->
         C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(340,5): error MSB3202: The project file "C:\Proj\MySolution.sln.metaproj" was not found. [C:\Proj\build.proj]
```

IS this scenario even supported?

**Comment by jeffkl** [comment]
I don't believe this is supported.  Traversal projects are supposed to be replacements for Visual Studio solution files so I would not recommend this.  

That said, Traversal just calls MSBuild to build the projects.  So if MSBuild supported having a `<ProjectReference />` to a solution file, this _should_ work.  Since it doesn't, I suspect its not supported.  This kind of makes sense, since a normal project would never want to "reference" a solution file since that pulls in a set of projects instead of a single one.

To have Traversal support this, it would need to have special logic to get the projects in a solution file and pass those to MSBuild.  If its a highly requested feature, we'd be open to adding it.

**Comment by jeffkl** [comment]
Closing as not supported.  You can open an issue at https://github.com/dotnet/msbuild to request a feature to allow dispatching a build of a solution file instead of a project via a `<ProjectReference />`
