### ISSUE TITLE
Are the msbuild sdk nuget package dependencies necessary

### ISSUE THREAD

**Issue by ViktorHofer** [microsoft/MSBuildSdks#431]
While looking at the latest available Traversal package on nuget.org, I noticed that the package contains empty dependency groups for `net40` and `netstandard2.0`. While this is just for cosmetics, I wonder if we want to omit them instead by setting `<SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>` in the project files.

Happy to submit a PR.

**Comment by jeffkl** [comment]
Technically it doesn't matter since `Microsoft.Build.Traversal` is a NuGet-based MSBuild Project SDK and during "restore" of this kind of package, NuGet does not respect dependencies or target framework compatibility.  I'm pretty sure you can't add a `<PackageReference />` to that kind of package either.

But if you want to submit a PR, I'll gladly accept it 😄

**Comment by ViktorHofer** [comment]
> Technically it doesn't matter since Microsoft.Build.Traversal is a NuGet-based MSBuild Project SDK and during "restore" of this kind of package, NuGet does not respect dependencies or target framework compatibility.

While NuGet doesn't respect it, we do have some tools that inspect packages and their dependencies, i.e. ApiCompat, or [SBRP](https://github.com/dotnet/source-build-reference-packages). I will submit a PR to suppress the dependencies.
