### ISSUE TITLE
IsCopyOnWriteSupported is overly restrictive

### ISSUE THREAD

**Issue by rainersigwald** [microsoft/MSBuildSdks#447]
I move my NuGet packages directory to another drive via

```cmd
mklink /j "C:\Users\raines\.nuget\packages" S:\nuget_packages\
```

This causes a false negative in `IsCopyOnWriteSupported`, because while there's no CoW support _on `C:`_, there is *from my NuGet packages folder*.

**Comment by MatthewSteeples** [comment]
Similarly, if you have mounted your REFS partition as a path rather than a drive letter this returns a false negative too (for the same reason)

**Comment by jeffkl** [comment]
@AndyGerlicher are you able to take a look?

**Comment by AndyGerlicher** [comment]
I'm not sure there's much we can do about this. Ideally, CloneFile would be implemented instead of copy at a lower level and just used when supported, but for now we need to check at some level to know which API to call.

Options I considered when copying `<path1>\foo.txt` to `<path2>\foo.txt`:
* Check for the same roots, check if CloneFile is supported, and then cache the result. If it fails, fallback to regular copy. This is what I ended up going with and it should have very little overhead.
* Check if supported for path1 to path2 each time Copy is invoked. This isn't free, I would really hate to slow things down. Those paths could be cached, but that would ultimately use more memory for path strings.
* Try to look up mount points and directory junctions and do some analysis to see if path1 and path2 are actually on the same volume.

If this becomes a big issue we could always revisit, but ultimately it's better to just move your package cache folder.

**Comment by MatthewSteeples** [comment]
As a side note (I recognise it's beyond the scope of the repository), is there an explanation for why the OS doesn't treat a file copy as a block clone? I've tried looking through the docs but haven't been able to find anything.
