### ISSUE TITLE
Add Target to Microsoft.Build.Traversal to generate Visual Studio Solution

### ISSUE THREAD

**Issue by jkoritzinsky** [Microsoft/MSBuildSdks#49]
As mentioned in the README, the Microsoft.Build.Traversal project files are meant as replacements for solution files. However, AFAIK neither VS or VSCode can open a dirs.proj file and load up the referenced projects as though a solution file was opened. It would be really useful for the user experience to be able to use MSBuild with the dirs.proj file to generate a solution file to work with for VS or VSCode.

**Comment by jeffkl** [comment]
Try this: https://github.com/jeffkl/SlnGen

**Comment by jkoritzinsky** [comment]
That'll work great! Thanks!

**Comment by kzu** [comment]
See also https://xamarin.github.io/mirepoix/articles/traversal-projects-with-solutions.html. @abock would it make sense to integrate that into this project itself?

**Comment by jeffkl** [comment]
SDKs should be as small as possible since MSBuild has to download them the first time during evaluation.  We are really against including any task assemblies in them.  That said, the SDK can add an implicit PackageReference just like how `.csproj` projects add one to `NETStandard.Library`.  We should merge the various implementations of solution generation and then add a PackageReference to it.
